### ISSUE TITLE
only cars ahead can be detected?

### ISSUE THREAD

**Issue by eraofelix** [jhultman/PV-RCNN#11]
Hi~
Now I can train and inference on my own dataset, it seems good but i am wondering why only cars ahead can be detected like this:
![image](https://user-images.githubusercontent.com/28798257/76144538-7f0e8e80-60bc-11ea-9930-842fe4fc85da.png)

 inference of PVRCNN and SECOND are both like this.
Thank you very much!

**Comment by eraofelix** [comment]
Maybe change of GRID_BOUNDS will work, i'll close this issue~

**Comment by eraofelix** [comment]
> Maybe change of GRID_BOUNDS will work, i'll close this issue~

sadly, it does not work, although i change GRID_BOUNDS to [-80, -40.0, -3, 80, 40.0, 2] both in training and inference

**Comment by jhultman** [comment]
Hmm, I'm not sure why this would happen. I think the only part of the code that would affect this is [here](https://github.com/jhultman/PV-RCNN/blob/master/pvrcnn/dataset/kitti_dataset.py#L88). Also [this](https://github.com/jhultman/PV-RCNN/issues/10) issue seems to suggest there is no problem with 360 degree inference. Maybe you accidentally load the ckpt from the model trained before grid_bounds fix?

**Comment by muzi2045** [comment]
if you only train on KITTI dataset, the result is normal, because the kitti annotations only exist in camera coordinates, which means only detect things only in front of the car. 
If you want to detect 360 degree things:
1. try to use Sample Augmentation, make every input training cloud have annotations in 360 degree.
2. just train on other dataset like Nuscenes.
3. do the inference twice for ahead 180 degree and rear 180 degree.
@eraofelix

**Comment by virajparimi** [comment]
@muzi2045 

Hi, can you explain more about the third alternative - inference twice one? Do you mean flipping the whole input pointcloud? How would that work?
